name: CI-CD

on:
    pull_request:
        branches:
            main
    push:
        branches:
            main

    # Allow manual trigger 
    workflow_dispatch:      

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with: 
                python-version: 3.12

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Format
              run: |
                black .

            - name: Lint
              run: |
                pylint --disable=R,C  main.py

            - name: Test App Code
              run: pytest

    cd:
      runs-on: ubuntu-latest
      needs: [ci]

      permissions:
        id-token: write
        contents: read

      steps:
        - name: Checkout to the branch
          uses: actions/checkout@v2

        - name: Azure Login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.PROYECTOMLOPS_AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.PROYECTOMLOPS_AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.PROYECTOMLOPS_AZURE_SUBSCRIPTION_ID }}

        - name: Set image tag with date and time
          run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

        - name: Build and push container image to registry
          uses: azure/container-apps-deploy-action@v2
          with:
            appSourcePath: ${{ github.workspace }}
            _dockerfilePathKey_: _dockerfilePath_
            registryUrl: docker.io
            registryUsername: ${{ secrets.PROYECTOMLOPS_REGISTRY_USERNAME }}
            registryPassword: ${{ secrets.PROYECTOMLOPS_REGISTRY_PASSWORD }}
            containerAppName: proyecto-mlops
            resourceGroup: MLOps
            imageToBuild: stinoco/proyecto-mlops:${{ env.IMAGE_TAG }}
            _buildArgumentsKey_: |
              _buildArgumentsValues_
